name: basic
description: Básico

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  intl: ^0.17.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.14
  easy_search_bar: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

  assets:
    - assets/images/

flutter_native_splash:
  color: "#0F4D7A"
  image: assets/images/splash-logo.png
  android: true 
  android12: true 
  ios: true

  android_12:
    image: assets/images/splash-logo.png
